---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"
  full:
    format:  "%(asctime)s - %(levelname)s - %(filename)s:%(funcName)s():%(lineno)d - %(message)s"

filters:
  show_only_info:
    (): for_logger.infoFilter
  show_only_warningerrorcritical:
    (): for_logger.warningErrorCriticalFilter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  all_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: log//all.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filters: [show_only_info]
    filename: log//info.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: full
    filename: log//errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8

loggers:
  my_module:
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, all_file_handler, info_file_handler, error_file_handler]

